openapi: 3.0.0
info:
  version: 0.1.0
  title: Raybot API
  description: >-
    The Raybot API
  license:
    url: https://opensource.org/licenses/MIT
    name: MIT
servers:
  - url: /api/v1
security: []
paths:
  /health:
    $ref: "./paths/health.yml"
  /error-codes:
    $ref: "./paths/error-codes.yml"
  /configs/log:
    $ref: "./paths/configs@log.yml"
  /configs/hardware:
    $ref: "./paths/configs@hardware.yml"
  /configs/cloud:
    $ref: "./paths/configs@cloud.yml"
  /configs/grpc:
    $ref: "./paths/configs@grpc.yml"
  /configs/http:
    $ref: "./paths/configs@http.yml"
  /configs/cargo:
    $ref: "./paths/configs@cargo.yml"
  /configs/wifi:
    $ref: "./paths/configs@wifi.yml"
  /system/reboot:
    $ref: "./paths/system@reboot.yml"
  /robot-state:
    $ref: "./paths/robot-state.yml"
  /peripherals/serials:
    $ref: "./paths/peripherals@serials.yml"
  /commands/{commandId}:
    $ref: "./paths/commands@{commandId}.yml"
  /commands:
    $ref: "./paths/commands.yml"
  /commands/processing:
    $ref: "./paths/commands@processing.yml"
  /commands/processing/cancel:
    $ref: "./paths/commands@processing@cancel.yml"
